spring:
  datasource:
    hikari:
      maximum-pool-size: 200
      driver-class-name: org.h2.Driver
      url: jdbc:h2:../test
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379
